# 📊 E-Commerce Sales Analytics Dashboard

## Day 1: Data Exploration

### Project Overview

This project focuses on analyzing e-commerce sales data to discover business insights using SQL, Python, and Power BI.

The workflow includes:

- Data Understanding
- Data Cleaning
- Exploratory Data Analysis (EDA)
- SQL Business Analysis
- Power BI Dashboard Development

---

## Objective

The objective of this analysis is to understand:

- Sales performance
- Customer behavior
- Product performance
- Regional trends
- Profitability patterns

---

## Tools Used

- Python
- Pandas
- NumPy
- Matplotlib
- Seaborn
- Jupyter Notebook

In [21]:
# Import required libraries

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

# Display settings
pd.set_option('display.max_columns', None)

print("Libraries imported successfully!")

Libraries imported successfully!

## 1. Loading Dataset

The dataset used in this project is the Superstore E-Commerce dataset.

The dataset contains information about:

- Shipping Mode
- Customer Segment
- Geographic Information
- Product Categories
- Product Sub-Categories
- Sales
- Quantity
- Discount
- Profit

In [22]:
# Load dataset

df = pd.read_csv("../data/raw/superstore.csv")

# Display first 5 rows

df.head()

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164

## 2. Dataset Overview

Checking:

- Number of rows and columns
- Available features
- Data types
- Missing values

In [23]:
# Dataset shape

df.shape

(9994, 13)

In [24]:
# Column names

df.columns

Index(['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Postal Code',
       'Region', 'Category', 'Sub-Category', 'Sales', 'Quantity', 'Discount',
       'Profit'],
      dtype='str')

In [25]:
# Dataset information

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Ship Mode     9994 non-null   str
 1   Segment       9994 non-null   str
 2   Country       9994 non-null   str
 3   City          9994 non-null   str
 4   State         9994 non-null   str
 5   Postal Code   9994 non-null   int64
 6   Region        9994 non-null   str
 7   Category      9994 non-null   str
 8   Sub-Category  9994 non-null   str
 9   Sales         9994 non-null   float64
 10  Quantity      9994 non-null   int64
 11  Discount      9994 non-null   float64
 12  Profit        9994 non-null   float64
dtypes: float64(3), int64(2), str(8)
memory usage: 1015.1 KB

## 3. Checking Missing Values

Missing values can affect analysis accuracy.

We will identify missing data before performing cleaning.

In [26]:
# Missing value count

df.isnull().sum()

Ship Mode       0
Segment         0
Country         0
City            0
State           0
Postal Code     0
Region          0
Category        0
Sub-Category    0
Sales           0
Quantity        0
Discount        0
Profit          0
dtype: int64

## 4. Duplicate Data Check

Duplicate records can create inaccurate business insights.

Checking duplicate rows:

In [27]:
# Duplicate rows

df.duplicated().sum()

np.int64(17)

## 5. Statistical Summary

Understanding numerical features:

- Sales distribution
- Profit distribution
- Quantity patterns
- Discount behavior

In [28]:
# Statistical summary

df.describe()

        Postal Code         Sales     Quantity     Discount       Profit
count   9994.000000   9994.000000  9994.000000  9994.000000  9994.000000
mean   55190.379428    229.858001     3.789574     0.156203    28.656896
std    32063.693350    623.245101     2.225110     0.206452   234.260108
min     1040.000000      0.444000     1.000000     0.000000 -6599.978000
25%    23223.000000     17.280000     2.000000     0.000000     1.728750
50%    56430.500000     54.490000     3.000000     0.200000     8.666500
75%    90008.000000    209.940000     5.000000     0.200000    29.364000
max    99301.000000  22638.480000    14.000000     0.800000  8399.976000

## 6. Basic Business Metrics

Initial understanding of the business:

- Total Sales
- Total Profit
- Total Orders

In [29]:
# Total Sales

total_sales = df['Sales'].sum()

print("Total Sales:", total_sales)

Total Sales: 2297200.8603

In [30]:
# Total Profit

total_profit = df['Profit'].sum()

print("Total Profit:", total_profit)

Total Profit: 286397.0217

In [31]:
# Total Transactions

total_transactions = len(df)

print("Total Transactions:", total_transactions)

Total Transactions: 9994

## Total Quantity Sold

Calculating total quantity of products sold.

In [32]:
total_quantity = df['Quantity'].sum()

print("Total Quantity Sold:", total_quantity)

Total Quantity Sold: 37873